<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Menhir</string>
    <key>fileTypes</key>
    <array>
      <string>mly</string>
    </array>
    <key>scopeName</key>
    <string>source.menhir</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>(?=%[^%])</string>
        <key>end</key>
        <string>(?=%%)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#declaration</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>%%</string>
        <key>beginCaptures</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.other.menhir</string>
          </dict>
        </array>
        <key>end</key>
        <string>%%</string>
        <key>endCaptures</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.other.menhir</string>
          </dict>
        </array>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#rule</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>include</key>
        <string>source.ocaml</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>declaration</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>%{</string>
            <key>beginCaptures</key>
            <array>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
            </array>
            <key>end</key>
            <string>%}</string>
            <key>endCaptures</key>
            <array>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
            </array>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ocaml</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>(%parameter|%start|%type|%token|%nonassoc|%left|%right|%on_error_reduce)\b</string>
            <key>name</key>
            <string>keyword.other.menhir</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)\s*([a-zA-Z][a-zA-Z0-9_]*)\s*(:)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.module.menhir</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ocaml</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>(&lt;)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ocaml#typedefs</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>rule</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([a-z][a-zA-Z0-9_]*)\s*(?:\(([^)]+)\))?(?=\s*:)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.rule.menhir</string>
              </dict>
              <key>2</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#ident</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>%public|%inline|%prec</string>
            <key>name</key>
            <string>keyword.other.directive.menhir</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>(:|\|)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?={)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variable</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#reference</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#operator</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.menhir</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ocaml</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.menhir</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\(\*</string>
            <key>end</key>
            <string>\*\)</string>
            <key>name</key>
            <string>comment.block.other.menhir</string>
          </dict>
        </array>
      </dict>
      <key>variable</key>
      <dict>
        <key>match</key>
        <string>([a-z][a-zA-Z0-9_]*)\s*=</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.value.menhir</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#reference</string>
          </dict>
        </array>
      </dict>
      <key>reference</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(?:[ibl]?option|pair|separated_pair|preceded|terminated|delimited|list|nonempty_list|separated_list|separated_nonempty_list)\b</string>
            <key>name</key>
            <string>support.function.rule.menhir</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#uident</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#lident</string>
          </dict>
        </array>
      </dict>
      <key>operator</key>
      <dict>
        <key>match</key>
        <string>[+*?|]</string>
        <key>name</key>
        <string>keyword.operator.menhir</string>
      </dict>
      <key>uident</key>
      <dict>
        <key>match</key>
        <string>[A-Z][a-zA-Z0-9_]*</string>
        <key>name</key>
        <string>entity.name.token.menhir</string>
      </dict>
      <key>lident</key>
      <dict>
        <key>match</key>
        <string>[a-z][a-zA-Z0-9_]*</string>
        <key>name</key>
        <string>entity.name.function.rule.menhir</string>
      </dict>
      <key>ident</key>
      <dict>
        <key>match</key>
        <string>[a-zA-Z][a-zA-Z0-9_]*</string>
        <key>name</key>
        <string>variable.parameter.rule.menhir</string>
      </dict>
    </dict>
  </dict>
</plist>
