<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ml</string>
		<string>mli</string>
	</array>
	<key>name</key>
	<string>OCaml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#hash_bang</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quoted_string_literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator_keyword</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.ocaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>comment</key>
					<string>string inside comment</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>{([a-z_]*)\|</string>
					<key>comment</key>
					<string>quoted string inside comment</string>
					<key>end</key>
					<string>\|\1}</string>
				</dict>
			</array>
		</dict>
		<key>hash_bang</key>
		<dict>
			<key>begin</key>
			<string>(#!)[ \t]*([^ ]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.hashbang.ocaml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.filename.ocaml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>multiline hashbang is not implemented</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.hashbang.multiline.ocaml</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(?:and|as|assert|begin|class|constraint|do|done|downto|else|end|exception|external|false|for|fun|function|functor|if|in|include|inherit|initializer|lazy|let|match|method|module|mutable|new|nonrec|object|of|open|or|parser|private|rec|sig|struct|then|to|true|try|type|val|virtual|when|while|with)\b</string>
			<key>name</key>
			<string>keyword.ocaml</string>
		</dict>
		<key>operator_keyword</key>
		<dict>
			<key>match</key>
			<string>\b(?:lor|lxor|mod|land|lsl|lsr|asr)\b</string>
			<key>name</key>
			<string>keyword.operator.ocaml</string>
		</dict>
		<key>quoted_string_literal</key>
		<dict>
			<key>begin</key>
			<string>{([a-z_]*)\|</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.delimiter.ocaml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\|\1}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.delimiter.ocaml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.ocaml</string>
		</dict>
		<key>string_literal</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.ocaml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\($|[\\'"ntbr ]|[0-9]{3}|o[0-3][0-7]{2}|x[0-9a-fA-F]{2})</string>
					<key>name</key>
					<string>constant.character.escape.ocaml</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.ocaml</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ocaml</string>
	<key>uuid</key>
	<string>F816FA69-6EE8-11D9-BF2D-000D93589AF6</string>
</dict>
</plist>
